name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ezauth-linux ./cmd/ezauth
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ezauth-mac ./cmd/ezauth
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ezauth-mac-arm ./cmd/ezauth
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.VERSION }}" -o ezauth.exe ./cmd/ezauth

      - name: Release & Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ezauth ${{ env.VERSION }}
          body: Release ${{ env.VERSION }}
          files: |
            ezauth-linux
            ezauth-mac
            ezauth-mac-arm
            ezauth.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use PAT here
